version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  gateway-api:
    image: fastapi-app-gateway:latest
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder
      - ./src/app/kaggle.json:/root/.kaggle/kaggle.json
      - ./reports/logs/app.log:/app/reports/logs/app.log #bind the app.log to one volume, all log messages are stored in this one log file (which is a copy in each container i.e. a bind mount to one local file)
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - update-api
      - train-api
      - predict-api
      - redis
    networks:
      - app-network

  train-api:
    image: fastapi-app-train:latest
    build:
      context: ./src/train
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder
      - ./src/app/kaggle.json:/root/.kaggle/kaggle.json
      - ./reports/logs/app.log:/app/reports/logs/app.log #bind the app.log to one volume, all log messages are stored in this one log file (which is a copy in each container i.e. a bind mount to one local file)
      - ./src/data:/app/../data #mount the data volume for storing the heartbeat data. IS THIS AN ERROR SOURCE? COPY INTO FOLDER!
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    
    networks:
      - app-network

  update-api:
    image: fastapi-app-update:latest
    build:
      context: ./src/update
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder. IS THIS NEEDED FOR UPDATE-API?
      - ./reports/logs/app.log:/app/reports/logs/app.log #bind the app.log to one volume, all log messages are stored in this one log file (which is a copy in each container i.e. a bind mount to one local file)
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - app-network


  predict-api:
    image: fastapi-app-predict:latest
    build:
      context: ./src/predict
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder
      - ./src/app/kaggle.json:/root/.kaggle/kaggle.json
      - ./reports/logs/app.log:/app/reports/logs/app.log #bind the app.log to one volume, all log messages are stored in this one log file (which is a copy in each container i.e. a bind mount to one local file)
      - ./src/data:/app/../data #mount the data volume for storing the heartbeat data. IS THIS AN ERROR SOURCE? COPY INTO FOLDER!
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    networks:
      - app-network
    

  mlflow:
    image: mlflow_server
    container_name: mlflow_server
    build:
      context: ./src/mlflow
      dockerfile: Dockerfile
    command: mlflow server --backend-store-uri /mlruns --default-artifact-root /mlruns --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder
      
    networks:
      - app-network

networks: #this is essential i.e. the only way i got the containers to communicate via service-names together (simon)
  app-network:
    driver: bridge
