version: '3.8'

services:
  gateway-api:
    image: fastapi-app:latest
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder
      - ./src/app/kaggle.json:/root/.kaggle/kaggle.json
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
      - update-api
    networks:
      - app-network

  update-api:
    image: fastapi-app-update:latest
    build:
      context: ./src/update
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network

  mlflow:
    image: mlflow_server
    container_name: mlflow_server
    command: mlflow server --backend-store-uri /mlruns --default-artifact-root /mlruns --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/../../mlruns #this seems to be the correct mlruns folder
      
    networks:
      - app-network

networks: #this is essential i.e. the only way i got the containers to communicate via service-names together (simon)
  app-network:
    driver: bridge
