#this docker-compose.yaml is written for the v1 of the docker-apis: Only one gateway api. this means, that all scripts must be on the same level as app.py aka in the /app folder.


version: '3.8'

services:
  fastapi:
    image: fastapi-app:latest
    build:
      context: ./src/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      #- ./mlruns:/app/mlruns #did not work because this leads to searching in the original directory tree which is not available in the container?
      - ./mlruns:/app/../../mlruns  # Mount the volume to the expected path
      - ./src/app/kaggle.json:/root/.kaggle/kaggle.json #WARNING: THIS IS SIMONS PERSONAL KAGGLE KEY! ONLY USE IN THIS PROJECT AND NEVER PUBLISH!
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow

  mlflow:
    image: mlflow_server
    container_name: mlflow_server
    command: mlflow server --backend-store-uri /mlruns --default-artifact-root /mlruns --host 0.0.0.0 --port 5000 #removed the /app before the /mlruns for consistency
    ports:
      - "5000:5000"
    volumes:
      #- ./mlruns:/app/mlruns #did not work because this leads to searching in the original directory tree which is not available in the container?
      - ./mlruns:/app/../../mlruns  # Mount the volume to the expected path
