# CI INTEGRATION TEST WITH GITHUB ACTIONS
# This will use the unit-tests or the test.py files inside the docker container environment
# Current Version: Tests only the train api with the test_train.py script
name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Launch docker compose
        run: |
          docker compose up -d
          sleep 10
      - name: Test train script with pytest
        run: |
          docker compose run api_train pytest -v tests/test_train.py
      - name: Close docker compose
        run: |
          docker compose down
